### PR TITLE
Fix react/http-client 0.4.13 response body issue

### LINKED ISSUE #17: Not working with react/http-client >= 0.4.13
| Q | A |
| --- | --- |
| Bug? | yes |
| New Feature? | no |
| Version |  |
#### Actual Behavior

This library return a error when creating an response
#### Expected Behavior

Working :)
#### Steps to Reproduce

Use last version of react/http-client
#### Possible Solutions

We should rework the way the response is build, it's no longer working since this PR has been merged into react/http-client https://github.com/reactphp/http-client/pull/66

### PR DESCRIPTION
**Pull request by shulard**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| BC breaks? | yes |
| Deprecations? | no |
| Related tickets | fixes #17 |
| Documentation |  |
| License | MIT |
#### What's in this PR?

This PR has been pushed to fixed the compatibility error with `react/http-client` v0.4.13.
#### Why?

There was a break change published in v0.4.13 around response body type. Before the first response body was sent as a `StreamInterface` instance, now it's "just" string.

Before we are using that `StreamInterface` instance as `$bodyStream`... Now it has been updated to use the `Http\Message\StreamFactory` to build a valid StreamInterface instance.

If a BC Break because I've introduced a new constructor parameter to be able to inject `StreamFactory` instance...

Of course the `Http\Discovery\StreamFactoryDiscovery` object is used when parameter is empty.

With this change, I've tested on lowest dependencies and it works too.
#### Checklist
- [ ] Updated CHANGELOG.md to describe BC breaks / deprecations | new feature | bugfix
#### To Do
- [x] Validate PR approach...
- [ ] Create a release with a composer update to disallow react/http-client > 0.4.12 ?

### CODE REVIEW

File: src/Client.php [hunk 1]
```diff
@@ -44,14 +46,21 @@ class Client implements HttpClient, HttpAsyncClient
...
      * Initialize the React client.
      *
      * @param ResponseFactory|null $responseFactory
+     * @param StreamFactory|null   $streamFactory
      * @param LoopInterface|null   $loop
      * @param ReactClient|null     $client
      */
     public function __construct(
         ResponseFactory $responseFactory = null,
+        StreamFactory $streamFactory = null,
```
Comment (joelwurtz) [inline src/Client.php]: This is BC Break, you should add it to the last parameter of the constructor, it would still be BC break but less given people may use the discovery system.

**Comment by joelwurtz** [comment]
If we use the StreamFactory as the last parameter of the constructor and we add php-http/message to the dependencies tree there will be no BC break, as react/http-client already include guzzle/psr7 interface and this library has a dependency on php-http/discovery then you will always have a StreamFactory service even if it was not injected.

**Comment by shulard** [comment]
Ok 😅 so I'll update my code!

**Comment by joelwurtz** [comment]
LGTM,

@dbu @sagikazarmark Ok for you ? IMO there is no bc break here.

**Comment by sagikazarmark** [comment]
As long as the comment above is resolved OK for me

File: src/Client.php [hunk 2]
```diff
@@ -94,17 +104,16 @@ public function sendAsyncRequest(RequestInterface $request)
         });
 
         $reactRequest->on('response', function (ReactResponse $reactResponse = null) use ($deferred, $reactRequest, $request) {
-            $bodyStream = null;
+            $bodyStream = $this->streamFactory->createStream();
             $reactResponse->on('data', function ($data) use (&$bodyStream) {
                 if ($data instanceof StreamInterface) {
-                    $bodyStream = $data;
+                    $bodyStream->write($data->getContents());
```
Comment (joelwurtz) [inline src/Client.php]: > Maybe I can use the incoming stream as $bodyStream like before ?

I think this will be very hard :/. There is no way to avoid memory problem here as react want us to work with data and not stream so the react interface block us from doing anything.

The only way to do that is to be sure that we create a stream using `php://temp` by example (not in memory, or at least not to much) and then read -> write by chunk of specified size (8192 is the best as it's the default chunk for PHP so there is no internal buffer).

But i don't think we should do this as the last version of react only give us data as a string and not a StreamInterface so this would be an enhancement for old version (so when people will update this lib with the enhancement they will certainly also update react/http-client which does not provide a StreamInterface anymore, so this enhancement will never be used...).

> Not to mention getContents reads the remainder, not the whole stream

:+1: We should only cast the stream to string `$bodyStream->write((string) $data);` in the same way that react as update it's library.

Comment (joelwurtz) [inline src/Client.php]: In fact you could remove the condition and only do : 

```
$bodyStream->write((string) $data);
```

**Comment by shulard** [comment]
I've updated the code with string cast, much simpler 😄.

File: composer.json [hunk 3]
```diff
@@ -16,7 +16,8 @@
         "react/http-client": "^0.4.8",
         "react/dns": "^0.4.1",
         "react/stream": "^0.4.3",
-        "php-http/discovery": "^1.0"
+        "php-http/discovery": "^1.0",
+        "php-http/message": "^1.0"
```
Comment (Nyholm) [inline composer.json]: Why is php-http/message added?

File: src/Client.php [hunk 4]
```diff
@@ -94,17 +104,12 @@ public function sendAsyncRequest(RequestInterface $request)
...
         $reactRequest->on('response', function (ReactResponse $reactResponse = null) use ($deferred, $reactRequest, $request) {
-            $bodyStream = null;
+            $bodyStream = $this->streamFactory->createStream();
             $reactResponse->on('data', function ($data) use (&$bodyStream) {
-                if ($data instanceof StreamInterface) {
-                    $bodyStream = $data;
-                } else {
-                    $bodyStream->write($data);
-                }
+                $bodyStream->write((string)$data);
```
Comment (Nyholm) [inline src/Client.php]: Code style: `(string) $data`

File: composer.json (hunk 3 above)
Comment (joelwurtz) [inline composer.json]: This library now require a StreamFactory to work which is added in the constructor, but it can be set to null and you the discovery system to work.

So if we keep it like that, this will be BC for people setting all the contrusctor parameters in order to avoid using Discovery, as the new parameter cannnot be found.

However `react/http-client` depends on ̀guzzlehttp/psr7` so by adding `php-http/message` we are sure to found a service for the StreamFactory in all cases so there is no BC.

Comment (Nyholm) [inline composer.json]: Okey, I've missed that discussion. 
I agree. But I would like to remove that line before tagging 1.0 (and preferably before tagging 0.3.0).

File: src/Client.php (hunk 4 above)
Comment (shulard) [inline src/Client.php]: Updated

**Comment by shulard** [comment]
Hello !

To address #20 in the same time (and avoid adding / moving the line in two different commits) I've already moved `php-http/message` dependency to `require-dev` section.

I also added a changelog update. If everyone is OK, I'll merge the PR asap.
