### PR TITLE
Fix composer version conflict with react/http v0.8

### LINKED ISSUE #25: Composer version conflict with react/http
| Q            | A
| ------------ | ---
| Bug?         | no
| New Feature? | no
| Version      | Latest

#### Actual Behavior

Composer `evenement/evenement` version conflict:
```
snogueira@snogueira:~/git/teste$ composer require react/http
Using version ^0.8.0 for react/http
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 12 installs, 0 updates, 0 removals
  - Installing react/promise (v2.5.1): Loading from cache
  - Installing evenement/evenement (v3.0.1): Loading from cache
  - Installing react/event-loop (v0.4.3): Loading from cache
  - Installing react/stream (v0.7.5): Loading from cache
  - Installing react/promise-stream (v1.1.0): Downloading (100%)         
  - Installing react/promise-timer (v1.2.0): Loading from cache
  - Installing react/socket (v0.8.6): Loading from cache
  - Installing react/dns (v0.4.11): Loading from cache
  - Installing react/cache (v0.4.1): Loading from cache
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing ringcentral/psr7 (1.2.1): Loading from cache
  - Installing react/http (v0.8.0): Downloading (100%)         
react/event-loop suggests installing ext-libevent (>=0.1.0)
react/event-loop suggests installing ext-event (~1.0)
react/event-loop suggests installing ext-libev (*)
Writing lock file
Generating autoload files
snogueira@snogueira:~/git/teste$ composer require php-http/react-adapter
Using version ^2.0 for php-http/react-adapter
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for php-http/react-adapter ^2.0 -> satisfiable by php-http/react-adapter[v2.0.0].
    - Conclusion: remove evenement/evenement v3.0.1
    - Conclusion: don't install evenement/evenement v3.0.1
    - php-http/react-adapter v2.0.0 requires react/http-client ^0.4.8 -> satisfiable by react/http-client[v0.4.10, v0.4.11, v0.4.12, v0.4.13, v0.4.14, v0.4.15, v0.4.16, v0.4.17, v0.4.8, v0.4.9].
    - react/http-client v0.4.10 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - react/http-client v0.4.11 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - react/http-client v0.4.12 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - react/http-client v0.4.13 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - react/http-client v0.4.14 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - react/http-client v0.4.15 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - react/http-client v0.4.16 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - react/http-client v0.4.17 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - react/http-client v0.4.8 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - react/http-client v0.4.9 requires evenement/evenement ~2.0 -> satisfiable by evenement/evenement[v2.0.0, v2.1.0].
    - Can only install one of: evenement/evenement[v2.0.0, v3.0.1].
    - Can only install one of: evenement/evenement[v2.1.0, v3.0.1].
    - Installation request for evenement/evenement (locked at v3.0.1) -> satisfiable by evenement/evenement[v3.0.1].


Installation failed, reverting ./composer.json to its original content.
```

#### Expected Behavior

No version conflict when requiring `php-http/react-adapter`

#### Steps to Reproduce

`composer init`
`composer require react/http`
`composer require php-http/react-adapter`

#### Possible Solutions

Update dependency on `react/stream` from `^0.4.3` to `^0.4` maybe?

### PR DESCRIPTION
**Pull request by samuelnogueira**
- Upgraded dependency on react/http-client
 - Introduced dependency on react/socket so \Http\Adapter\React\buildDnsResolver and \Http\Adapter\React\buildHttpClient remain usable as before (no need for major version bump on php-http/react-adapter)

| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | no
| BC breaks?      | no
| Deprecations?   | no
| Related tickets | fixes #25 
| License         | MIT

#### What's in this PR?

Upgraded dependency on react/http-client
Introduced dependency on react/socket so \Http\Adapter\React\buildDnsResolver and \Http\Adapter\React\buildHttpClient remain usable as before (no need for major version bump on php-http/react-adapter)

### CODE REVIEW

File: src/ReactFactory.php [hunk 1]
```diff
@@ -54,13 +55,26 @@ public static function buildDnsResolver(
     public static function buildHttpClient(
         LoopInterface $loop,
         DnsResolver $dns = null
+    ) {
+        $dnsConnector = static::buildDnsConnector($loop, $dns);
```
Comment (dbu) [inline src/ReactFactory.php]: did the react client constructor signature change to expect the dns connector instead of the dns resolver? no auto-instantiation?

if so, we should probably follow the pattern of the DnsResolver and add another optional parameter for the connector. hm, but $dns is never needed when you pass the whole connector. maybe remove the typehint from $dns and do instanceof to see if its the resolver or the connector? and deprecate passing only the resolver?

File: composer.json [hunk 2]
```diff
@@ -13,9 +13,10 @@
     "require": {
         "php": "^5.5 || ^7.0",
         "php-http/httplug": "^1.0",
-        "react/http-client": "^0.4.8",
+        "react/http-client": "^0.5",
```
Comment (dbu) [inline composer.json]: can we keep allowing 0.4.8 or are there BC breaks?

Comment (samuelnogueira) [reply composer.json]: Unfortunately there are: https://github.com/reactphp/http-client/releases/tag/v0.5.0
Furthermore, `\React\HttpClient\Client`'s constructor signature has changed, so even calling it directly instead of using `Factory` won't work the same in v0.4 and v0.5.

Comment (dbu) [reply composer.json]: okay. i suggest we bump the minor version of this library then, and deprecate passing the dns resolver but still support it (see my comment above)

File: src/ReactFactory.php (hunk 1 above)
Comment (samuelnogueira) [reply src/ReactFactory.php]: > did the react client constructor signature change to expect the dns connector instead of the dns resolver? no auto-instantiation?
Yes it did. There is auto-instantiation though, the dns connector could be omitted, and we could simply deprecate the entire $dns param for the `buildHttpClient` method, however, wouldn't this be a major version bump? Also, the ability to control the dns connector/resolver instance would be lost (was it even needed in the first place?).

About your suggestion, doing the `instanceof` of the second `buildHttpClient` parameter to allow either the connector or the dns resolver to be passed looks like a good solution, to maintain retro-compatibility + IoC for the connector instance, I'll push a commit with that change.

**Comment by samuelnogueira** [comment]
Since we are introducing a new public method `\Http\Adapter\React\ReactFactory::buildDnsConnector`, which is added functionality, I think it makes sense to up the MINOR version.

File: src/ReactFactory.php (hunk 1 above)
Comment (dbu) [reply src/ReactFactory.php]: i would just add the flexibility but deprecate passing the resolver and recommend to pass the connector. i think the factory should keep allowing a custom dns resolution tool.

in a version 2 we can then add the typehint for the connector and thus drop dns resolver support in the http client factory method.

File: composer.json (hunk 2 above)
Comment (joelwurtz) [reply composer.json]: I think we can be BC here and keep 0.4.8 by checking if this `React\HttpClient\Factory` class exists, then use old behavior in that case, otherwise use the new behavior

File: src/ReactFactory.php [hunk 3]
```diff
@@ -43,24 +44,45 @@ public static function buildDnsResolver(
...
     public static function buildHttpClient(
         LoopInterface $loop,
-        DnsResolver $dns = null
+        $connector = null
     ) {
-        if (null === $dns) {
-            $dns = self::buildDnsResolver($loop);
+        // build a connector if none is given, or create one attaching given DnsResolver (old deprecated behavior)
+        if (null === $connector || $connector instanceof DnsResolver) {
+            $connector = static::buildConnector($loop, $connector);
```
Comment (joelwurtz) [inline src/ReactFactory.php]: I think we should only build connector if it's a Resolver, when it's null we should let React do this job as it's an optional argument (less code to maintain as we don't have to follow the default behavior of react of creating a dns connector)

File: src/ReactFactory.php [hunk 4]
```diff
@@ -43,24 +45,93 @@ public static function buildDnsResolver(
...
+     * @param DnsResolver|ConnectorInterface|null $connector
+     *
+     * @return HttpClient
+     */
+    private static function buildHttpClient05(
+        LoopInterface $loop,
+        $connector = null
+    ) {
+        // build a connector with given DnsResolver if provided (old deprecated behavior)
+        if ($connector instanceof DnsResolver) {
```
Comment (dbu) [inline src/ReactFactory.php]: can you please add a deprecation warning inside the if?

`@trigger_error(sprintf('Passing a %s to buildHttpClient is deprecated since version 2.1.0 and will be removed in 3.0. If you need no specific behaviour, omit the $dns argument, otherwise pass a %s', DnsResolver::class, ConnectorInterface::class), E_USER_DEPRECATED);`

File: src/ReactFactory.php [hunk 5]
```diff
@@ -43,24 +45,93 @@ public static function buildDnsResolver(
...
+            : new Connector($loop);
+    }
+
     /**
      * Build a React Http Client.
      *
-     * @param LoopInterface $loop
-     * @param DnsResolver   $dns
+     * @param LoopInterface                       $loop
+     * @param ConnectorInterface|DnsResolver|null $connector Passing a DnsResolver instance is deprecated. Should pass a
```
Comment (dbu) [inline src/ReactFactory.php]: i think we should be more specific. say: "Only pass this argument if you need to customize DNS behaviour. With react 0.5, pass a connector, wth react 0.4 this must be a DnsResolver."

File: src/ReactFactory.php [hunk 6]
```diff
@@ -43,24 +45,93 @@ public static function buildDnsResolver(
...
+    ) {
+        // create dns resolver if one isn't provided
         if (null === $dns) {
-            $dns = self::buildDnsResolver($loop);
+            $dns = static::buildDnsResolver($loop);
+        }
+
+        // validate connector instance for proper error reporting
+        if (!$dns instanceof DnsResolver) {
+            throw new \InvalidArgumentException('$connector must be an instance of DnsResolver');
```
Comment (dbu) [inline src/ReactFactory.php]: Here we should say `For react 0.4, $dns must be an instance of DnsResolver`
